import img from '../../assets/courses/preview.png'
import img1 from '../../assets/courses/preview1.png'
import profile from '../../assets/courses/profilepic.png'

export let courses = [
    {
        video: img,
        title: 'Envato Mastery: Build a Passive Income...',
        chapter: '3',
        part: '2',
        head: 'Evanto Mastery',
        mentor: 'Ms Nina',
        duration: '4h 23m',
        profile: profile,
        progress: 79,
        students: 52,
        bookmarks: 16,
        watched: 41,
    },
    {
        video: img1,
        title: 'Envato Mastery: Build a Passive Income...',
        chapter: '3',
        part: '2',
        head: 'Evanto Mastery',
        mentor: 'Ms Nina',
        duration: '4h 23m',
        profile: profile,
        progress: 79,
        students: 52,
        bookmarks: 16,
        watched: 41,
    },
    {
        video: img1,
        title: 'Envato Mastery: Build a Passive Income...',
        chapter: '3',
        part: '2',
        head: 'Evanto Mastery',
        mentor: 'Ms Nina',
        duration: '4h 23m',
        profile: profile,
        progress: 79,
        students: 52,
        bookmarks: 16,
        watched: 41,
    },
    {
        video: img1,
        title: 'Envato Mastery: Build a Passive Income...',
        chapter: '3',
        part: '2',
        head: 'Evanto Mastery',
        mentor: 'Ms Nina',
        duration: '4h 23m',
        profile: profile,
        progress: 79,
        students: 52,
        bookmarks: 16,
        watched: 41,
    },
    {
        video: img1,
        title: 'Envato Mastery: Build a Passive Income...',
        chapter: '3',
        part: '2',
        head: 'Evanto Mastery',
        mentor: 'Ms Nina',
        duration: '4h 23m',
        profile: profile,
        progress: 79,
        students: 52,
        bookmarks: 16,
        watched: 41,
    }
]